# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccea610db3b68ef547f5a0ae38515337481e51b8ea9dfe04aaaab60b4a3a97bed196feac527539ef733e1c9c03cdfd1896b19bd3d1040833dcec877889c36417

test:
  secret_key_base: 67bdc54707234ba38a8a254db07d29db0f379023246f927460a04ee41b219c0e0514b89ccae421efd562386be5a7efb9d0de68ae344f2bba7d7e536d1eebb7f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
